### ISSUE TITLE
rgl.snapshot only renders window corner --- ubuntu

### ISSUE THREAD

**Issue by pauljeco** [dmurdoch/rgl#112]
Hi,
I'm having trouble exporting an image or `rgl.snapshot` of a 3D snapshot.
I have tried adjusting these parameters: window size, viewpoint zoom and aspect using e.g.

```
rgl::par3d("windowRect" =  c(0, 0, 2400, 2400))
rgl::aspect3d(x = 25, y = 25, z = 25)
rgl::rgl.viewpoint(zoom = .5)
rgl::rgl.snapshot("data/3d_test.png")
```

The output image is consistently limited to the upper left corner of the rgl window:
![m80_geom_rs](https://user-images.githubusercontent.com/53813755/122209359-baddf980-cea4-11eb-985b-c5e207e1de3f.png)

Where the full image taken using a system screen shot is:
![m80_geom](https://user-images.githubusercontent.com/53813755/122209703-1c05cd00-cea5-11eb-886a-14e02c85d639.png)

This has been reported before but from within the 'rayshader' package which I used to produce these images. Note that running the example code in [this issue](https://github.com/tylermorganwall/rayshader/issues/96) I get the same problem as reported there: this was noted to be an issue with rgl. The code from that example is below:

```
x <- sort(rnorm(1000))
y <- rnorm(1000)
z <- rnorm(1000) + atan2(x, y)
plot3d(x, y, z, col = rainbow(1000))
par3d(windowRect = c(0,0,600,600))
rgl::rgl.snapshot("test.png")
```

Thank you very much for rgl!

* **rgl Version 0.106.23**:
* **R Version 4.1.0**:
* **Platform**: running ubuntu 20.04 on local machine

Here is a copy of my system environment output from R
[sys_env.txt](https://github.com/dmurdoch/rgl/files/6662613/sys_env.txt)

**Comment by dmurdoch** [comment]
Have you tried installing `webshot2` and using `snapshot3d`?

**Comment by dmurdoch** [comment]
I've just fired up an old system running Ubuntu 18.0.4, and didn't see any problem with your second example.  So my guess would be that your system is reporting the window size in a different way than rgl expects.  Maybe you have a Retina (or whatever Ubuntu calls it) display with more pixels than are reported?  In that case, I suspect `webshot2` is your best bet, but you could try some low level debugging yourself and put together a patch so `rgl` gets the sizing right.

**Comment by pauljeco** [comment]
Thanks so much for your rapid response here! I'm going to stick with the 'webshot' option. After installing the Chrome web browser and `webshot2` --> snapshot3d is working.
