### ISSUE TITLE
Rmarkdown embed fails with javascript error

### ISSUE THREAD

**Issue by richarddmorey** [dmurdoch/rgl#127]
I'm trying to run the simple Rmarkdown example given in https://bookdown.org/yihui/rmarkdown-cookbook/rgl-3d.html. The full Rmarkdown source is:

````
---
title: "rgl"
output: 
  html_document
---

```{r setup, include=FALSE}
# https://bookdown.org/yihui/rmarkdown-cookbook/rgl-3d.html
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```

```{r, test-rgl, webgl=TRUE, echo=FALSE}
x <- sort(rnorm(1000))
y <- rnorm(1000)
z <- rnorm(1000) + atan2(x,y)
plot3d(x, y, z, col = rainbow(1000))
```
````

When I compile it, there is no plot. 

![Screenshot 2021-08-19 184057](https://user-images.githubusercontent.com/1284826/130117767-9b22b3ab-171f-4690-a24f-536e6704856f.png)

When I mouse over where the plot should be, I get a "grab hand" mouse cursor (the `canvas` is there). As you can see in the image, there is a javascript error, `Uncaught TypeError: vertices[best] is undefined`, that appears to happen here: 

https://github.com/dmurdoch/rgl/blob/2292744227211ed3e2dea72f47f43dcca2abfabb/inst/htmlwidgets/lib/rglClass/axes.src.js#L54

I swear this used to work recently, but I tried it with the CRAN version of rgl (0.107.10), the previous version (0.106.6), and the current development version on GitHub, and the result is the same: no plot. (In 0.106.6, oddly, I don't see the javascript error, but I still don't see a plot).

I can also confirm that this does work from the R console (I get the popup window with the plot in it).

---
System details:
* **rgl Version**: Tried with 0.106.6, 0.107.10, and GitHub version downloaded today.
* **R Version**: 4.1.0
* **Platform**: Windows 10 (64-bit)
* **Browser**: Firefox 91.0 (64-bit)
 
```
> xfun::session_info()
R version 4.1.0 (2021-05-18)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043), RStudio 1.4.1717

Locale:
  LC_COLLATE=English_United States.1252 
  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252
  LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  askpass_1.1       base64enc_0.1.3  
  brew_1.0.6        brio_1.1.2       
  bslib_0.2.5.1     cachem_1.0.5     
  callr_3.7.0       cli_3.0.1        
  clipr_0.7.1       commonmark_1.7   
  compiler_4.1.0    crayon_1.4.1     
  credentials_1.3.1 crosstalk_1.1.1  
  curl_4.3.2        desc_1.3.0       
  devtools_2.4.2    diffobj_0.3.4    
  digest_0.6.27     ellipsis_0.3.2   
  evaluate_0.14     fansi_0.5.0      
  fastmap_1.1.0     fs_1.5.0         
  gert_1.3.2        gh_1.3.0         
  gitcreds_0.1.1    glue_1.4.2       
  graphics_4.1.0    grDevices_4.1.0  
  highr_0.9         htmltools_0.5.1.1
  htmlwidgets_1.5.3 httpuv_1.6.2     
  httr_1.4.2        ini_0.3.1        
  jquerylib_0.1.4   jsonlite_1.7.2   
  knitr_1.33        later_1.3.0      
  lazyeval_0.2.2    lifecycle_1.0.0  
  magrittr_2.0.1    markdown_1.1     
  memoise_2.0.0     methods_4.1.0    
  mime_0.11         openssl_1.4.4    
  pillar_1.6.2      pkgbuild_1.2.0   
  pkgconfig_2.0.3   pkgload_1.2.1    
  praise_1.0.0      prettyunits_1.1.1
  processx_3.5.2    promises_1.2.0.1 
  ps_1.6.0          purrr_0.3.4      
  R6_2.5.1          rappdirs_0.3.3   
  rcmdcheck_1.3.3   Rcpp_1.0.7       
  rematch2_2.1.2    remotes_2.4.0    
  renv_0.13.2       rgl_0.107.10     
  rlang_0.4.11      rmarkdown_2.10   
  roxygen2_7.1.1    rprojroot_2.0.2  
  rstudioapi_0.13   rversions_2.1.1  
  sass_0.4.0        sessioninfo_1.1.1
  shiny_1.6.0       sourcetools_0.1.7
  stats_4.1.0       stringi_1.7.3    
  stringr_1.4.0     sys_3.4          
  testthat_3.0.4    tibble_3.1.3     
  tinytex_0.33      tools_4.1.0      
  usethis_2.0.1     utf8_1.2.2       
  utils_4.1.0       vctrs_0.3.8      
  waldo_0.2.5       whisker_0.4      
  withr_2.4.2       xfun_0.25        
  xml2_1.3.2        xopen_1.0.0      
  xtable_1.8-4      yaml_2.2.1       
  zip_2.2.0  
```

**Comment by dmurdoch** [comment]
Sorry, didn't notice this when you posted it (I was on vacation).  Your example works for me with the devel version, but I'd recommend against using the obsolete `webgl=TRUE` method to include the plot.  Run `setupKnitr(autoprint = TRUE)` in a chunk, and the plots will happen automatically.
