### ISSUE TITLE
Bad rendering of colored "sphere" symbols in html outputs

### ISSUE THREAD

**Issue by sdray** [dmurdoch/rgl#135]
IDear all.

Thanks for your excellent work on rgl. For some courses, I use some rgl code in Rmd documents. I notice that the rendering of 3D plots has been modified so that representations with `type = 's'` returns black circles instead of colored spheres. See for instance the page at `https://dmurdoch.github.io/rgl/articles/WebGL.html`

Do you know how to solve this problem (graphics in rgl window are correct).

Cheers

**Comment by dmurdoch** [comment]
I don't see the issue you're talking about -- the spheres display properly for me.  Could you be more specific, and/or include a screenshot of what you're seeing?

**Comment by sdray** [comment]
Sorry for the partial description. I did not know if the problem was related to building or the display of the plots. It seems that it is the display that did not work well. Here is what I obtain:
![image](https://user-images.githubusercontent.com/13961612/134171050-78100a3c-b353-435a-8540-da3a9cb8fc65.png)

I obtain the same black circles on Firefox 92.0, Chrome 93.0.4577.82  and Rstudio Viewer on my fresh install (July) of Ubuntu 20.04.3 LTS

Sorry to bother you, as it seems to be more a system/browser problem than an rgl issue.

**Comment by dmurdoch** [comment]
That's likely an issue with the GPU driver.  You might get some kind of hint about it if you look at the browser console log.  

It could still be an rgl issue:  I may be making assumptions that don't hold on your system, but I don't really know what they would be.

You could try the Github version.  There has been one bug fix that might be relevant:  

   * `shade3d()`, `wire3d()` and `dots3d()` overrode
     `"front"` and `"back"` material settings in mesh objects.

though I kind of doubt it.

**Comment by sdray** [comment]
Thanks. I think that you are right. I have a new dell laptop and it seems that drivers for GPU are not (yet) fully available. I tried to update the BIOS, update the OS (21.04) and rgl from github but no changes. I think that I should wait for new drivers for ubuntu.

Thanks you answer.
Cheers
