### ISSUE TITLE
texture mapping not compatible with 'meshColor = "faces"

### ISSUE THREAD

**Issue by mdsumner** [dmurdoch/rgl#145]
A query, texture mapping doesn't work when `faces` is used for `meshColor`.  Should it still work the same or is this material property incompatible? 

(the image is stretched or mangled depending on the scale and image details ...)

For various reasons I had 'faces' as a default, so I thought my mappings were broken ... but as 'vertices' it all works as expected. 

```R
texture <- system.file("textures/worldsmall.png", package = "rgl", mustWork = TRUE)


 library(rgl)
 vertices <- matrix(c( 
          -1.0, -1.0, 0,
           1.0, -1.0, 0,
           1.0,  1.0, 0,
          -1.0,  1.0, 0
       ), 3)
       indices <- c( 1, 2, 3, 4 )
       material <- list(texture = texture, color = "#FFFFFF")
texcoords <- cbind(c(0, 1, 1, 0), c(0, 0, 1, 1))
open3d()  

## works fine
mesh <- mesh3d(vertices = vertices, quads = indices, material = material, texcoords = texcoords)
## not fine
faces <-  mesh3d(vertices = vertices, quads = indices, material = material, texcoords = texcoords, meshColor = "faces")
open3d()
plot3d(mesh) 
open3d() 
plot3d(faces)
```

* **rgl Version**:  0.107.14
* **R Version**:  4.1.1
* **Platform**: Linux -- 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/4107631/137568023-4184c19c-6923-4f7d-91d2-95a626d8a9ce.png)

**Comment by dmurdoch** [comment]
This was documented behaviour in `?shade3d`, but I think it doesn't make sense.  PR#146 changes it.

**Comment by mdsumner** [comment]
Thank you! (Recent changes in rgl are really awesome btw, so much excellent stuff, very much appreciated).

**Comment by mdsumner** [comment]
I confirm it works, checked with a few cases. Thanks very much.

**Comment by dmurdoch** [comment]
Thanks for the report, it's now in the main branch.
