### ISSUE TITLE
Points3D not plotting points but squares, not responding to PCH

### ISSUE THREAD

**Issue by hana777** [dmurdoch/rgl#156]
Hi all,

I'm using the newest R and also the latest verison of Rstudio. Im trying to plot xyz data (cells) with points3D. It always worked previously. Lately, I started getting trouble with it. By default, the points3d version will plot little cubes, also the quality and rendering of the images is pretty bad. I cant turn it into circles at all. Previously, the default option would be a point, but now its cubes, and it cannot be changed, not even by using PCH.

Does anybody know what is the root of this problem? I need to plot circles.

**Comment by dmurdoch** [comment]
The `points3D` function is not in `rgl`, only `points3d` is.  But it's not at all clear what code you are using.  Please include sample code to illustrate the issue (and if your code uses `points3D`, you're asking in the wrong place).

**Comment by hana777** [comment]
Hi, sorry for having used points3D in the first line. I use points3d.

points3d(coords, col = 'salmon1', size = 6.0) 

![image](https://user-images.githubusercontent.com/35686767/139721366-0b48837b-d0d3-48dd-9451-ef60b15dab4b.png)

Coords exist of x y z coordinates. It has always worked. My problem is it doesn't plot circles anymore.

**Comment by dmurdoch** [comment]
There's no PCH argument to `points3d`.  There's a `pch3d` function, and it can draw circles.  For example,

    pch3d(1:10, 1:10, 1:10, pch = 16, cex = 0.5)

which produces this:

![Screen Shot 2021-11-01 at 3 51 25 PM](https://user-images.githubusercontent.com/1935680/139732741-3feddb8a-421d-41b4-a713-336746c4b6cf.png)

The points come out a little too large, but you can use a smaller value of `cex` to shrink them.

**Comment by hana777** [comment]
Thanks so much!
