### ISSUE TITLE
Enhancement:  allow JPEGs to be loaded as textures

### ISSUE THREAD

**Issue by dmurdoch** [dmurdoch/rgl#196]
Found in the rgl2gltf project:  some glTF files use JPEG textures, but rgl doesn't support those.

**Comment by dmurdoch** [comment]
It might make sense to do this by allowing arrays as textures; then the user could read the texture any way they liked.

**Comment by SbastianGarzon** [comment]
This would be a great feature. I'm not sure if it is directly related, but It would be useful to allow multiple textures. Right now I'm using "simple" OBJ objects to create 3D visualizations (rayshader), but having more detailed objects would improve visualization' quality.

For example, using {rayshader} would be nice to have more detailed [trees](https://free3d.com/3d-model/tree-67970.html):

`render_obj("Tree/Tree.obj", lat= 5, lon= 4, altitute=10, extent = raster::extent(cropped_data),heightmap = elevation_matrix,zcale=1,load_material = TRUE)`

Is it possible to think that it will be feasible in the future to import such detailed objects?

**Comment by dmurdoch** [comment]
A lot more will become possible once rgl uses shaders for everything.  The main difficulty will be giving users an understandable way to get what they want.

**Comment by dmurdoch** [comment]
Fixed in #347 .

**Comment by mdsumner** [comment]
Awesome 😎
