### ISSUE TITLE
Can't insert line breaks into axis labels

### ISSUE THREAD

**Issue by ferenci-tamas** [dmurdoch/rgl#198]
Running `rgl::plot3d(rnorm(20), rnorm(20), rnorm(20), xlab = "a\nb")` produces an axis label without a line break. (A space replaces the newline character.) I don't whether this is strictly speaking a bug or not (i.e., whether this was _supposed_ to be supported), but usual `plot` has no problem with such line breaks, see `plot(rnorm(20), rnorm(20), xlab = "a\nb")`.

* **rgl Version**: 0.108.26
* **R Version**: 4.2.1
* **Platform**:  Windows 10

**Comment by dmurdoch** [comment]
No, line breaks aren't supported.  To do what you want you'll need to use `mtext3d`, for example

```
library(rgl)
plot3d(rnorm(20), rnorm(20), rnorm(20), xlab = "")

mtext3d(c("a", "b"), edge = "x++", floating = TRUE, line = c(4, 5.5))
```

The `line` argument says how far the two labels should be from the axis.  `line=4` is the default for an axis label; `5.5` is 1.5 lines further.

If you don't want the labels to move as the ticks move, set floating to `FALSE`, and choose `edge` according to where you want the labels to be drawn.

**Comment by ferenci-tamas** [comment]
Thank you very much! The only problem I see with this solution is that even with `floating = FALSE` the alignment changes with the viewpoint. Which looks great when viewed interactively, but can be strange in a static snapshot, for instance, the text might look completely right-aligned depending on the perspective. Is it possible to achieve left (or center) alignment for all viewpoints...?

**Comment by dmurdoch** [comment]
Okay, I understand what you want.  You should be able to do that with `plotmath3d`.  For example,

    plot3d(rnorm(20), rnorm(20), rnorm(20), xlab = expression("line 1\nline 2"))

Unfortunately, this isn't working in the current devel version, because the addition of marginal arguments messed it up a bit.  That should be an easy bug to fix, but we'll see.
