### ISSUE TITLE
Rotating a graph shows axis labels on the wrong axis

### ISSUE THREAD

**Issue by hughjonesd** [dmurdoch/rgl#202]
The following code 

```r
f <- function(x, y) { 
  r <- sqrt(x^2 + y^2)
  ifelse(r == 0, 10, 10 * sin(r)/r)
}

um <- matrix(c(0.63775003,  -0.7701848, -0.009502447, 0,
               0.04336312,   0.0235839,  0.998780727, 0,
              -0.76902151,  -0.6373846,  0.048438177, 0,
               0, 0, 0, 1), 
             4, 4, byrow = TRUE)
invisible(rgl::open3d(zoom = 0.75, userMatrix = um, windowRect = c(0, 45, 578, 502)))
rgl::plot3d(
             f,
             xlim = c(0, 0.95),
             ylim = 1:2, 
             zlab = "Correlation"
           )
```

shows a picture like this:
![Screenshot 2022-04-06 at 12 37 45](https://user-images.githubusercontent.com/5818871/161966376-df1597f4-9a97-4c42-92c6-ed7ae6775916.png)

This has the x and y axis labels on the same axis, which is surely wrong.

Omitting the call to `open3d()`, or just the `userMatrix` argument, puts the labels on the right axis.

Apologies if I've misunderstood something.

* **rgl Version**: 0.108.3
* **R Version**: 4.1.0
* **Platform**: MacOS

**Comment by dmurdoch** [comment]
I see that with 0.108.3, but not in any later devel builds.  I did fix a number of bugs relating to axis labels; though I don't recall seeing this particular symptom, I guess one of the other bug fixes caught it too.

The current master branch is on 0.108.30 now; I'd recommend using that if you can install it.  If you can't get it to build, let me know and I'll put a binary build on the drat site.

**Comment by dmurdoch** [comment]
Sorry, this isn't actually a bug, it's an optical illusion.  The x axis label and ticks in your illustration are actually on the top edge of the left-hand back face.  Due to perspective, the left-hand front face is bigger, so its top edge appears higher than the top edge of the back face.
