### ISSUE TITLE
Error in `webshot2::webshot` - unused argument (top = FALSE)

### ISSUE THREAD

**Issue by psychemedia** [dmurdoch/rgl#21]
Running `rgl::snapshot3d(filename = temp, top = bring_to_front)` from `rayshader::render_snapshot()` or `rayshader::render_movie()` was working but now throws an error: `Error in webshot2::webshot(f1, file = filename, selector = "#webshot", : unused argument (top = FALSE)`

```
3. capture.output(webshot2::webshot(f1, file = filename, selector = "#webshot", vwidth = width + 100, vheight = height, ...), type = "message")

2. rgl::snapshot3d(filename = temp, top = bring_to_front)

1. render_snapshot(hi_quality_fn, samples = 200, top = FALSE, scale_text_size = 24, clear = FALSE)

```

**Comment by dmurdoch** [comment]
Yes, I messed up the new params to `snapshot3d`.  Will fix soon.  In the meantime, adding `webshot = FALSE` to the arguments would work around the error (but does require changes to `rayshader::render_snapshot`).

**Comment by psychemedia** [comment]
Thanks:-)
