### ISSUE TITLE
[Feature Request] Additive Blending

### ISSUE THREAD

**Issue by marvinschmitt** [dmurdoch/rgl#245]
Thanks for the great package! It would be great to support **additive blending** (and potentially other blending modes).
Since changing the blending mode to _additive_ in OpenGL is as easy as

```
glEnable(GL_BLEND);
glBlendFunc(GL_SRC_ALPHA, GL_ONE);
```

, I would expect this to be a rather straightforward feature to implement. Thank you for your time!

**Comment by dmurdoch** [comment]
I'll consider a PR for this, but it's not something that I'm likely to do myself soon. 

If you do put together a PR, it won't be as simple as you are suggesting:  currently all blending is the same so it's done at the subscene level; the natural way to do this would be as a material property, done at the individual object level.  And don't forget to do it in the Javascript as well.
