### ISSUE TITLE
rglwidgetOutput and/or rglwidget broken?

### ISSUE THREAD

**Issue by nialsiG** [dmurdoch/rgl#249]
Hello,
Since the last R major update (4.2) I cannot seem to output my rgl graphs into shiny apps. At first, I thought it was my app, but when I run demo("simpleShinyRgl") I have the same problem. I get 4 pop-up windows with the following message:

![error_capture](https://user-images.githubusercontent.com/45664241/178461811-eb5e741b-0b22-4227-bf1e-addf4f1ae3d3.PNG)

I tried to build it as a window, or in different browsers - it did not solve. I also tried both the latest CRAN and the github versions. As a sidenote, it actually works with older R versions.

For completion's sake, I am on R 4.2.1 (but 4.2.0 had the same issue), OS: Windows 10 Pro, R studio: 2022.02.1 Build 461

Best regards!

**Comment by dmurdoch** [comment]
Thanks for the report.  I get the same error; I'll try to track it down.

**Comment by dmurdoch** [comment]
Are you able to test the fix on your real code?  You'll need to install directly from Github, using

    remotes::install_github("dmurdoch/rgl@issue249")

If that doesn't work, let me know your R version and platform, and I may be able to build a binary package for you, which would be easier to install.

**Comment by nialsiG** [comment]
The problem is fixed both for the demo and my app - I guess taht the issue can be closed.
Good job!
