### ISSUE TITLE
rgl examples don't display in pkgdown

### ISSUE THREAD

**Issue by dmurdoch** [dmurdoch/rgl#25]
For a nice display, this will likely need changes in pkgdown (see https://github.com/r-lib/pkgdown/issues/1256), but we can have a hack similar to this one sooner:  https://github.com/r-lib/pkgdown/issues/1256#issuecomment-618352673.

**Comment by dmurdoch** [comment]
I have submitted a PR:  https://github.com/r-lib/pkgdown/pull/1548 .  To try it out, you need to use the `rglpatch` branches of `pkgdown` and `downlit`, via

    remotes::install_github(c("dmurdoch/downlit@rglpatch", "dmurdoch/pkgdown@rglpatch", "dmurdoch/rgl"))

This version won't get the sizes of figures right.  If you want to try a version that does, try

    remotes::install_github(c("dmurdoch/downlit@rglpatch", "dmurdoch/pkgdown@figures", "dmurdoch/rgl@pkgdfigs"))

With those changes, `rgl` figures will be sized according to the settings in the `figures` section of the `_pkgdown.yml` file.

There's also a version of `htmlwidgets` that works with these changes:   try

    remotes::install_github(c("dmurdoch/downlit@rglpatch", "dmurdoch/pkgdown@rglpatch", "dmurdoch/htmlwidgets@rglpatch"))

if you want to include other kinds of `htmlwidgets` (e.g. `leaflet`, `plotly`) in your `pkgdown` site.  

No sizing there yet.

**Comment by zhenglukai** [comment]
> I have submitted a PR: [r-lib/pkgdown#1548](https://github.com/r-lib/pkgdown/pull/1548) . To try it out, you need to use the `rglpatch` branches of `pkgdown` and `downlit`, via
> 
> ```
> remotes::install_github(c("dmurdoch/downlit@rglpatch", "dmurdoch/pkgdown@rglpatch", "dmurdoch/rgl"))
> ```
> 
> This version won't get the sizes of figures right. If you want to try a version that does, try

Hi @dmurdoch , I am a bit confused. Which one is working, "dmurdoch/pkgdown@figures" or "dmurdoch/pkgdown@rglpatch"?

**Comment by dmurdoch** [comment]
They both work, but the one in the PR doesn't allow you to control the size of your rgl figures, so if you want that, `dmurdoch/pkgdown@figures` works somewhat better. Is that an important feature to you?  Would you want the size of rgl figures to be different than other plots?  It can't do that, but it would probably be possible to add it.

**Comment by zhenglukai** [comment]
Thank you for the explanation. Yes, I think control of the rgl figures would be a useful feature.

**Comment by dmurdoch** [comment]
Then you should use the "figures" branch.  Let me know if you have problems.

**Comment by dmurdoch** [comment]
BTW, I'll probably merge the figures branch into the rglpatch branch this week, so there will be no difference.

**Comment by dmurdoch** [comment]
Current branches to use:  r-lib/downlit, r-lib/pkgdown, dmurdoch/htmlwidgets@rglpatch.

**Comment by dmurdoch** [comment]
A change to pkgdown in June broke this again, so the current branches to use are r-lib/downlit, dmurdoch/pkgdown@issue1689, and dmurdoch/htmlwidgets@rglpatch .

**Comment by dmurdoch** [comment]
And recent fixes have it working again.  Still not the CRAN version, though.

**Comment by dmurdoch** [comment]
All working now.
