### ISSUE TITLE
Question: is it possible to embed rgl window into a tcltk frame? 

### ISSUE THREAD

**Issue by hongyuanjia** [dmurdoch/rgl#280]
This may be a dumb question, but I did not find the answer on the Internet. I would like to embed an rgl window into a tcltk frame and add buttons to control what geometries to show using rgl. However, it looks that current implementation like tkspin3d creates a new tcltk frame instead of reusing the rgl window. My question is, is that possible to let tcltk directly use the rgl window? Thanks!

**Comment by dmurdoch** [comment]
As far as I know that's not (currently) possible.  Many years ago I tried to do it, but was unsuccessful in getting `rgl` to work with TCL/TK windows.  I haven't worked with TCL/TK much, so that might be just because of my ignorance.

**Comment by hongyuanjia** [comment]
Thanks for the quick response. Looks like I found that thread on [Sourceforge](https://sourceforge.net/p/tcl/mailman/tcl-core/thread/44D3F36A.8040905%40pobox.com/).

> I haven't worked with TCL/TK much

I saw there were lots of commits on the webgl support. That is totally understandable, since everyone wants to run things in a browser. But TCL/TK may also have its market, considering R's built-in support for TCL/TK.

Shall I close this issue or leave it open?

**Comment by dmurdoch** [comment]
I think that was a different effort, but it happened around the same time.  In that case I wanted TCL/TK to embed its windows in Rgui.  What you are asking for is to embed rgl in a TCL/TK window.  

I think there's no chance I'll attempt this again, so I'll close the issue.  If someone else who knows TCL/TK internals wants to take it on, they could open it again.
