### ISSUE TITLE
implementation of shinySelectionInput in rglwidget

### ISSUE THREAD

**Issue by ZacharySMorris** [dmurdoch/rgl#30]
I have noticed that in the shinyGetPar3d documentation there is a reference to a "shinySelectionInput" argument for the rglwidget function. However, I cannot find this argument in the rglwidget function itself or anywhere else in the rgl documentation. Is this something that is in progress? Or was this something that has been removed?

I ask, as I am interested in building a shiny application which would extract coordinates on a mesh object based on the position of a mouse click on a rglwidgetOutput. This seems like something which would be relevant to this, but I can find no way to implement this argument. Is there someway to get such an output from the rglwidget, via this argument or any other set of functions?

This is my first issue submission, so please excuse me if this is an inappropriate use of this mechanism. Thank you for your continued work on this incredibly useful R package!

**Comment by gitdemont** [comment]
Hi,

You may be interested in this demo to address your question
https://github.com/dmurdoch/rgl/blob/master/demo/shinyMouse.R

It shows how to create a brush selection for your rgl visualization in a shiny app.
You can then retrieve brushing information and indices of points selected.

HTH

**Comment by ZacharySMorris** [comment]
I have attempted to run the demo code, but receive an error that the "shinyResetBrush" function is not found. Is this not loaded in rgl version 0.103.5?

**Comment by dmurdoch** [comment]
No, it was added in 0.104.x.  The current CRAN version 0.105.13 has it.

**Comment by ZacharySMorris** [comment]
Ah, I see that now. Thanks!
