### ISSUE TITLE
Detect if WebGL is supported by the user browser

### ISSUE THREAD

**Issue by gitdemont** [dmurdoch/rgl#31]
Hi,

I recently came into troubles using rgl R package into a shiny app I am currently developing.
This had nothing to do with rgl package itself but rather with webgl that was not supported by my browser.

I solved this by adding some javascript in my app to check webgl availability.
Maybe it could be nice to add an alert or something alike if so ?

Here is something adapted from: https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/By_example/Detect_WebGL

avlWebGL = function() {
var canvas=document.createElement('canvas');
var gl=canvas.getContext('webgl')||canvas.getContext('experimental-webgl');
var ans=!!(false | (gl && gl instanceof WebGLRenderingContext));
if(!ans) alert('webgl is not supported by your browser');
return ans;
};

Best,

**Comment by dmurdoch** [comment]
There was already a test for WebGL here:  https://github.com/dmurdoch/rgl/blob/0352a6f2526d31464f23c96352c7b1baa5d4d94f/inst/htmlwidgets/lib/rglClass/init.src.js#L6 but your test will detect diferent issues, so I'll add it.

**Comment by gitdemont** [comment]
Oops, since I got an issue with webgl support I did not imagine that there was already a test for that
Nice if this can catch more (I hope all) issues with webgl support

**Comment by dmurdoch** [comment]
Could you please test the new version on the system that had the WebGL problems?
