### ISSUE TITLE
auto closing

### ISSUE THREAD

**Issue by rb643** [dmurdoch/rgl#313]
I'm aware all the `rgl.` function are now deprecated but was wondering if there is an alternative to rgl.cur() and rgl.close() as I found those quite useful in cleaning up all active open windows.

**Comment by dmurdoch** [comment]
`cur3d` is identical to `rgl.cur`.  `close3d` is not identical, but is a replacement for `rgl.close`.

**Comment by rb643** [comment]
Thanks! This solves my issue so just posting this here for future reference in case its useful for others:
```
while (length(rgl::rgl.dev.list())>0 ) { rgl::close3d() }
```
