### ISSUE TITLE
arc3d is incomplete when n is missing

### ISSUE THREAD

**Issue by stla** [dmurdoch/rgl#369]
Hello, 

When we don't set `n` in `arc3d`, the arc does not join the two points:

```r
library(rgl)

A <- c(0, 0, 1)
B <- c(0, 1, 0)

arc3d(A, B, c(0, 0, 0), 1, lwd = 3)

points3d(rbind(A, B), size = 12)
```

* **rgl Version**: 1.1.15
* **R Version**: 4.3.0
* **Platform**: Linux Mint 20

**Comment by dmurdoch** [comment]
I believe this is fixed in #374.  Thanks for the report!
