### ISSUE TITLE
`addNormals` warnings

### ISSUE THREAD

**Issue by stla** [dmurdoch/rgl#372]
Hello,

I have [this mesh](https://gist.github.com/stla/01a49bf1926d03888888b2abd8a7ef0f) (you can read it with `Rvcg::vcgPlyRead`). 

When I do `addNormals(mesh)`, I have some warnings:

```
1: In acos(dot/veclen(a)/veclen(b)) : NaNs produced
2: In acos(dot/veclen(a)/veclen(b)) : NaNs produced
......
```

I find it's strange because I don't see what is bad in this mesh.

When I do `addNormals(mesh, angleWeighted = FALSE)`, there's no warning.

There's also an angle weighted method in the **Rvcg** package (`Rvcg::vcgUpdateNormals(mesh, type=1)`), it works without errors/warnings.

**Comment by dmurdoch** [comment]
I think that's caused by rounding error.  In the first case, the `dot/veclen(a)/veclen(b)` value comes out to `1 + 2e-16`, and `acos` gives `NaN` as the answer.  I'll force the values to the range -1 to 1.  

Thanks for the report.
