### ISSUE TITLE
helots fails because of issue with rgl

### ISSUE THREAD

**Issue by skreibig** [dmurdoch/rgl#446]
Registered S3 methods overwritten by 'rgl':
  method               from
  knit_print.rglId         
  knit_print.rglOpen3d     
  sew.rglRecordedplot      
Error in dyn.load(dynlib <- getDynlib(dir)) : 
  unable to load shared object '/Users/skreibig/Library/R/arm64/4.4/library/rgl/libs/rgl.so':
  dlopen(/Users/skreibig/Library/R/arm64/4.4/library/rgl/libs/rgl.so, 0x0006): Library not loaded: /opt/X11/lib/libGLU.1.dylib
  Referenced from: <C3FB2FAF-8517-3EBF-A366-EAF5C1C74ED7> /Users/skreibig/Library/R/arm64/4.4/library/rgl/libs/rgl.so
  Reason: tried: '/opt/X11/lib/libGLU.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/X11/lib/libGLU.1.dylib' (no such file), '/opt/X11/lib/libGLU.1.dylib' (no such file), '/usr/local/lib/libGLU.1.dylib' (no such file), '/usr/lib/libGLU.1.dylib' (no such file, not in dyld cache)
Error: package or namespace load failed for ‘heplots’:
 .onLoad failed in loadNamespace() for 'rgl', details:
  call: rgl.init(initValue, onlyNULL)
  error: OpenGL is not available in this build
In addition: Warning messages:
1: 	Loading rgl's DLL failed. 
	This build of rgl depends on XQuartz, which failed to load.
 See the discussion in https://stackoverflow.com/a/66127391/2554330 
2: Trying without OpenGL... 
trying URL 'https://ftp.osuosl.org/pub/cran/bin/macosx/big-sur-arm64/contrib/4.4/rgl_1.3.14.tgz'
Content type 'application/x-gzip' length 12344990 bytes (11.8 MB)
==================================================
downloaded 11.8 MB

**Comment by dmurdoch** [comment]
You need to post some details of what you were doing when this error message came.
