### ISSUE TITLE
mesh3d() and/or readOBJ() no longer works with certain textured meshes

### ISSUE THREAD

**Issue by trevorld** [dmurdoch/rgl#89]
In the latest CRAN release of ``rgl`` (as well as the current development version) it seems that ``mesh3d()`` or perhaps ``readOBJ()`` no longer works with certain textured meshes that previously worked with earlier ``rgl`` CRAN releases (in particular versions 0.100.47 through 0.105.22):

````
# textured rectangular prism
obj_file <- "# geometric vertices
v 1 1 -0.125
v 1 -1 -0.125
v -1 -1 -0.125
v -1 1 -0.125
v 1 1 0.125
v 1 -1 0.125
v -1 -1 0.125
v -1 1 0.125
# texture coordinates
vt 0.025 1
vt 0.025 0
vt 0.425 0
vt 0.425 1
vt 0.575 1
vt 0.575 0
vt 0.975 0
vt 0.975 1
vt 0.52 0
vt 0.48 0
vt 0.48 1
vt 0.52 1
# Textured polygonal face element
f 1/1 2/2 3/3 4/4
f 5/5 8/8 7/7 6/6
f 6/9 7/10 3/11 2/12
f 7/9 8/10 4/11 3/12
f 8/9 5/10 1/11 4/12
f 5/9 6/10 2/11 1/12"
writeLines(obj_file, "tile_back.obj")

library("rgl")
open3d()
mesh <- readOBJ("tile_back.obj")
shade3d(mesh)
````

````
Warning in max(inds) : no non-missing arguments to max; returning -Inf
Error in rep_len(vals, max(inds)) : invalid 'length.out' value

Enter a frame number, or 0 to exit   

1: shade3d(mesh)
2: shade3d.mesh3d(mesh)
3: getArgs(x$it)
4: cbind(repfn(texcoords[, 1], inds, FALSE), repfn(texcoords[, 2], inds, FALSE
5: repfn(texcoords[, 1], inds, FALSE)
````

* **rgl Version**: 0.106.7
* **R Version**: 4.0.4
* **Platform**: Linux 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021

**Comment by dmurdoch** [comment]
Thanks, I see this.  It happened in the mesh3d cleanup on Mar 31 (commit bad0384af...; I guess I should have paid attention to the SHA!).  I expect it'll be easy to fix.

**Comment by trevorld** [comment]
Thanks!  I confirm that this fixes my downstream bug.

This bug triggered CRAN check errors on my package and  CRAN (Prof. Ripley) says I must "correct" my package by May 2nd in order for it to stay up on CRAN.  Are you planning on releasing a patch to CRAN soon?  Or should I just go ahead and disable (for now) the examples and tests that depend on rgl so my package can pass the CRAN package checks?  Thanks!

**Comment by dmurdoch** [comment]
I replied by email, but I'm not sure that made it through.

I'll likely wait until next week to submit an `rgl` update.  Two bugs have shown up in the last one; if more show up, that may be delayed further.

Which package of yours did this affect?  I do reverse dependency checks and didn't see it.

**Comment by trevorld** [comment]
This affected the package ``piecepackr``: https://cran.r-project.org/web/checks/check_results_piecepackr.html

**Comment by dmurdoch** [comment]
Thanks.  It didn't install during my reverse dependency checks, so I didn't see the problem.

I've been doing revdep checks using R-devel, but that means I have to build everything from source.  The builds of `rayrender` and `vdiffr` failed (presumably they need libs that I don't have), so `piecepackr` wouldn't install.  Not sure why CRAN's checks didn't tell me about it; maybe they just do a sampling.

**Comment by trevorld** [comment]
> The builds of rayrender and vdiffr failed (presumably they need libs that I don't have)

In case this is helpful here is the current list of (Ubuntu) development libraries I need to install in my Travis CI configuration for ``piecepackr``:

* libmagick++-dev
* libgit2-dev
* libgl1-mesa-dev 
* libglu1-mesa-dev

I suspect the missing libs needed by vdiffr/rayrender is ``libgit2``.  This is a dependency of the ``gert`` package which is a relatively new dependency of some tidyverse packages.   I suddenly needed to install these headers about four months ago to keep my test scripts working.

**Comment by dmurdoch** [comment]
On 19/04/2021 2:11 a.m., Trevor L Davis wrote:
> Thanks! I confirm that this fixes my downstream bug.
> 
> This bug triggered CRAN check errors on my package and CRAN (Prof. 
> Ripley) says I must "correct" my package by May 2nd in order for it to 
> stay up on CRAN. Are you planning on releasing a patch to CRAN soon? Or 
> should I just go ahead and disable (for now) the examples and tests that 
> depend on rgl so my package can pass the CRAN package checks? Thanks!

A new version (0.106.8) has now been accepted by CRAN.  Hopefully 
nothing new comes up!

Duncan Murdoch

**Comment by trevorld** [comment]
Thanks!  The ERROR message for my package does seem to be gradually going away as v0.106.8 slowly makes its way to the various CRAN test nodes.
