### ISSUE TITLE
feature request: hover in rgl

### ISSUE THREAD

**Issue by gitdemont** [dmurdoch/rgl#99]
Hi,

Would it be possible to include a plot_hover to rgl like in shiny::plotOutput in the same manner as what has been done within https://github.com/dmurdoch/rgl/blob/master/demo/shinyMouse.R

I did some tries with sprites to show images within rgl scene (see https://r-forge.r-project.org/forum/forum.php?thread_id=34099&forum_id=757&group_id=234)
However, when there are a lots of objects to be displayed, the rendering is highly impacted and interaction with the scene tends to be impossible.

Another solution could be to display an image on hover.
I saw https://stackoverflow.com/questions/43368444/r-interactive-3d-plotly-scatterplot-rgl-style-with-hover-info but it was about plotly and I finally can't find any solution to this.

So, I did some work on it using built-in rgl functions to determine closest point with mouse coordinates (and derivatives based on rglwidgetClass.prototype.selectionChanged and identify3d), see attached rgl_hover.zip file

I used a div of class rglWegGL-hover that is inserted / removed during hover next to the closest vertex.
Besides hover information are sent to R through input$rgl_3D_hover, allowing other elements to be inserted / removed to DOM by R functions insertUI / removeUI
As an example, I had <img> inside the .rglWegGL-hover div

There are some limitations, because it is not fully included in rgl, (I have attached events to #plot_3D and it is not part of https://github.com/dmurdoch/rgl/blob/master/inst/htmlwidgets/lib/rglClass/mouse.src.js so it may compete with other listeners).
And, for instance on scene rotation / zoom the hovering info become wrong until the mouse hovers the scene again.
I choosed to remove the .rglWegGL-hover on these actions rather than computing the resulted translation.
Finally, on the contrary to what happen with selection which is included inside the canvas context, so dragging (for scene rotation) may be interupted when the mouse enter the div.

Best,

[rgl_hover.zip](https://github.com/dmurdoch/rgl/files/6409296/rgl_hover.zip)

**Comment by dmurdoch** [comment]
One way to do this would be to construct the images/text for every point and plot them all with `alpha=0` so they are invisible.  Then set up some Javascript to find the closest point(s) and make that/those labels visible.

Another way would be to construct one object, and change both alpha and location in response to mouse moves.  That would only allow one label, but maybe that's what you want.

The hardest part in either of these would be to set up the mouse handler, which should be written in Javascript for fast response.   Currently the WebGL code doesn't support "user" mode for mouse handlers. That would need to be added.

**Comment by gitdemont** [comment]
1st solution may indeed do the trick. 
In addition, since everything is created with the widget it may be the best way when user wants to save it

2nd solution is close to what I have attached inside the zip except that I am not using alpha but rather a div that is inserted removed on mouse move next to the closest point. Obviously with this 'placeholder' object inside the widget and the javascript that position it correctly inside the canvas on mouse move the limitations I mentioned would be overridden.

However, I did some testing with a solution based on rgl.addToSubscene()/rgl.delFromSubscene() and rgl.drawScene() but the interactivity was rapidly impacted due to the deluge of mousemove (but I may not have done it the correct way). This is why I shifted to the div solution.

Maybe a mixed of both 1 and 2 would be nice:
-a place in the rgl widget where to store vertices, labels and eventually base64 image during the creation (like rglShared that writes the crosstalk), lets say rgl.hover that contains x, y, z, meta.label, meta.alt-text, meta.img
-the object you described that is positionned on mouse to the closest of those vertices and retrieves and displays associated meta infomation of this closest vertex (+ controls on text size and image scaling)
-and eventually a way to allow custom injection of meta infomation inside this object through R based on an observer on input$rgl_3D_hover. If there is a response from R to input$rgl_3D_hover change then widget will use it instead of  what can be found inside rgl.hover

**Comment by dmurdoch** [comment]
I am pretty sure any solution involving shiny will currently be too slow to work on mouse movements.  There's a lot of overhead involved in communications with R.  It'll also have the disadvantage of only working in a shiny app, not in a general web page.

I think a more fruitful approach would be to add the necessary support for doing it all in Javascript.  That takes some careful design; users shouldn't be expected to understand all the internals of the rglClass functions, and I shouldn't be locked into the current implementation.

**Comment by gitdemont** [comment]
Here (see the zip) is an ugly workaround for a standalone solution
[rgl_hover_standalone.zip](https://github.com/dmurdoch/rgl/files/6409575/rgl_hover_standalone.zip)

I attached base64 uri during widget creation wdg <- rglwidget(); wdg$x$meta <- base64
Then the javascript only looks in rgl.scene.meta for images and rgl.scene.crosstalk,key for labels (vertices are within rgl.scene.obj)

I think doing so should work in a general web page as long as the javascript is included (either directly thanks to a dedicated rgl function or thanks to fo example htmlwidgets::onRender)

Concerning, the overhead, I did some tries with the first zip I attached (I tried with 5000 points and inserting/removing the img on the fly was still highly responsive, as long as JS is used to compute closest point)
Indeed, I tried also to compute the closest point within R or within JS in response to mouse position or and JS was clearly the winner

I understand the point of the internals of rgl functions. And this is why, I am writing here, because I know that the things I rely on to do the JS functions in my examples may be broken in future rgl release.

Besides, this new example is still based on adding a div on top on the canvas and not based on the solution you mentioned with the repositionning and alpha tweak on the object, which I think should be a better one.

**Comment by dmurdoch** [comment]
I've just done some work that's related to this in the `userMouse` branch.  It adds a 5th entry to `par3d("mouseMode")`, which is the mode to use when no button is pressed.

For scenes displayed in `rgl` windows in R, this should allow R code to be attached, though I haven't tried that yet and may have missed something.

For widgets in HTML pages, it has the same limitation as other mouse modes:  only the pre-coded ones are currently supported (though the same sort of hacking should allow you to add your own).

There's one odd bug that I know about:  when you produce the rgl widget in RStudio it appears in the viewer pane, but
the response to mouse movement is sometimes not activated until you click on some other application and then return to RStudio.  I don't really have any idea about the cause of this; currently it seems to be avoidable by using `options(rgl.useNULL = TRUE)`, but I'd rather have a better fix.

The more interesting case of user-coded handlers written in Javascript is the next thing to work on.

**Comment by gitdemont** [comment]
Sorry for the delay (I am and will be far from a computer for some days)

I have just installed the branch without any problem.
I can get mouse position from standalone widget and also within a shiny app (i.e. what is sent to console.log())
I tested mouse mode 'none' and 'trackball'. I don't know if it is an expected behaviour but mouse position is also sent to console.log  when the scene is being dragged.

For rgl window (no widget), I was not able to set / get  MouseCallbacks (through rgl.setMouseCallbacks or rgl.getMouseCallbacks) on button 4. Maybe the no button mode should be set / get in an other way

Yes it will be super cool if there can be a rgl.setMouseCallbacks equivalent for the rglwidget returned object.
I searched the rglwidgetClass in JS for .handlers but was not able to find it. As far as I understood, they are produced by setMouseHandlers. It may be an entry point to apply user-coded with arguments like setMouseHandlers("mousemove", user defined function) to call a function created by the user, setMouseHandlers("mousemove", default) to restore the rgl default behaviour and setMouseHandlers("mousemove", false) to stop listening. For the moment, this function has no argument.

Best,

**Comment by dmurdoch** [comment]
The console messaging is just for debugging purposes; it will go away when all done.

Thanks for the info about the callbacks.  I'll fix that.

**Comment by gitdemont** [comment]
New installation today.
Everything is working smoothly.

Console messaging disappeared in widget and I was able to use  rgl.setMouseCallbacks(button = 4, ...)
I used a modified version of the pan3d() example described in rgl.setMouseCallbacks documentation. (just had to removed activeSubscene <- par3d("activeSubscene", dev = dev), because with no click there is no activeSubscene)

Thanks to you for all this work to include hiver feature to rgl !

**Comment by dmurdoch** [comment]
I think the latest commit to the userMouse branch should allow this to be written.  It still needs testing and doc improvements.

The idea for a hover method would be to write both R code and Javascript to handle the mouse update event for the "default" button.  (That's really the "no" button; maybe I will rename it.)  Then call setUserCallbacks("default", update = "methodname", javascript = "window.methodname = function(x, y) { .... }") to install it.

**Comment by gitdemont** [comment]
I followed the recent commit history. It was stunning.
It is much more than just 'hover' since it seems to allow user to register their own callbacks.

I agree with you for the name 'default' -> 'no'
In addition, I would also eventually use button = 0 for this 'no' button. Maybe this is more self explanatory.
However this may result in many changes in the rgl code.

I have just installed the latest version of userMouse branch.
Now, I will try things out and tell you.

**Comment by dmurdoch** [comment]
Those suggestions both make sense.  I was reluctant to do the renumbering because I thought I would miss some cases in the code, but I went ahead and did it.  So now "no button" is named `"none"`, and is button 0 if specified numerically.  I'll wait a while before merging, because there may be some bugs left.

**Comment by gitdemont** [comment]
It is really amazing. THANKS a lot for all this - I did not test with the latest commit : 'Big renaming'.

Until the version before this commit, I was not really able to figure out how to apply what you described with the alpha = 0.
Now thanks to the new example with the text3d, I got it and was even able to use it with sprites see 
[rgl_with_callback.zip](https://github.com/dmurdoch/rgl/files/6455044/rgl_with_callback.zip)

**Comment by gitdemont** [comment]
Hi,

I got a small issue with the latest rgl version
When, on hover cursor is 'grab' (normal behaviour)
Then, if we rotate the scene, cursor is 'grabbing' (normal behaviour)
Once, the rotation is ended, cursor is still 'grabbing' instead of being 'grab'
Only a mouse move allows cursor to be set back to 'grab'

A min reprex:
library(rgl)
open3d(useNULL = TRUE)
plot3d(x = rnorm(10),y = rnorm(10),z = rnorm(10), type = "s")
rglwidget()

In addition, if a callback is set like in example(topic = "setUserCallbacks", package = "rgl"), but on button = "none" instead of "left", the cursor is never set back to 'grab'

**Comment by dmurdoch** [comment]
This should be fixed in #107.
